import "./globals.css";

// Components
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata = {
  title: "Portfolio 03",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative font-crimson">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
